%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.1

-ifndef(opentelemetry_zipkin_pb).
-define(opentelemetry_zipkin_pb, true).

-define(opentelemetry_zipkin_pb_gpb_version, "4.21.1").


-ifndef('ZIPKIN_SPAN_PB_H').
-define('ZIPKIN_SPAN_PB_H', true).
-record(zipkin_span,
        {trace_id = <<>>        :: iodata() | undefined, % = 1, optional
         parent_id = <<>>       :: iodata() | undefined, % = 2, optional
         id = <<>>              :: iodata() | undefined, % = 3, optional
         kind = 'SPAN_KIND_UNSPECIFIED' :: 'SPAN_KIND_UNSPECIFIED' | 'CLIENT' | 'SERVER' | 'PRODUCER' | 'CONSUMER' | integer() | undefined, % = 4, optional, enum zipkin_span.Kind
         name = <<>>            :: unicode:chardata() | undefined, % = 5, optional
         timestamp = 0          :: non_neg_integer() | undefined, % = 6, optional, 64 bits
         duration = 0           :: non_neg_integer() | undefined, % = 7, optional, 64 bits
         local_endpoint = undefined :: opentelemetry_zipkin_pb:zipkin_endpoint() | undefined, % = 8, optional
         remote_endpoint = undefined :: opentelemetry_zipkin_pb:zipkin_endpoint() | undefined, % = 9, optional
         annotations = []       :: [opentelemetry_zipkin_pb:zipkin_annotation()] | undefined, % = 10, repeated
         tags = []              :: [{unicode:chardata(), unicode:chardata()}] | undefined, % = 11
         debug = false          :: boolean() | 0 | 1 | undefined, % = 12, optional
         shared = false         :: boolean() | 0 | 1 | undefined % = 13, optional
        }).
-endif.

-ifndef('ZIPKIN_ENDPOINT_PB_H').
-define('ZIPKIN_ENDPOINT_PB_H', true).
-record(zipkin_endpoint,
        {service_name = <<>>    :: unicode:chardata() | undefined, % = 1, optional
         ipv4 = <<>>            :: iodata() | undefined, % = 2, optional
         ipv6 = <<>>            :: iodata() | undefined, % = 3, optional
         port = 0               :: integer() | undefined % = 4, optional, 32 bits
        }).
-endif.

-ifndef('ZIPKIN_ANNOTATION_PB_H').
-define('ZIPKIN_ANNOTATION_PB_H', true).
-record(zipkin_annotation,
        {timestamp = 0          :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         value = <<>>           :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-ifndef('ZIPKIN_LIST_OF_SPANS_PB_H').
-define('ZIPKIN_LIST_OF_SPANS_PB_H', true).
-record(zipkin_list_of_spans,
        {spans = []             :: [opentelemetry_zipkin_pb:zipkin_span()] | undefined % = 1, repeated
        }).
-endif.

-ifndef('ZIPKIN_REPORT_RESPONSE_PB_H').
-define('ZIPKIN_REPORT_RESPONSE_PB_H', true).
-record(zipkin_report_response,
        {
        }).
-endif.

-endif.
